# Generated by Django 2.0.7 on 2021-01-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalType', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedType', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/')),
                ('animal', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
                ('breed', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='animals.Breed')),
            ],
        ),
    ]
