# Generated by Django 2.0.7 on 2021-01-19 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalType',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breedType',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Animal'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Breed'),
        ),
    ]
