# Generated by Django 2.0.7 on 2021-01-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20210118_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='name',
            new_name='animalType',
        ),
    ]
