# Generated by Django 2.0.7 on 2021-01-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20210118_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='animalDetails',
        ),
    ]
