# Generated by Django 2.0.7 on 2021-01-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20210118_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='animalDetails',
            new_name='breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Animal'),
        ),
    ]
