# Generated by Django 2.0.7 on 2021-01-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20210118_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='zipCode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
