# Generated by Django 2.0.7 on 2021-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_auto_20210120_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='pictures/', width_field='width'),
        ),
    ]
